name: Bug report
description: Report a reproducible problem in igw-cli.
title: "[bug] "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened and what did you expect?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Include exact commands and flags.
      placeholder: |
        1. igw ...
        2. igw ...
    validations:
      required: true
  - type: textarea
    id: output
    attributes:
      label: Actual output
      description: Paste output and exit code. Mask any secrets.
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: OS, shell, Go version (if built from source), and igw version.
      placeholder: |
        OS:
        Shell:
        igw version:
